name: Deploy domain portal

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: qed-artifacts/qed-public-platform/.github/workflows/deploy-domain.yml@main
